# Generated by Django 3.2.15 on 2022-10-06 18:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kechkilar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kechki',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, help_text='matn kiriting'),
        ),
        migrations.AlterField(
            model_name='kechki',
            name='photo',
            field=models.ImageField(blank=True, help_text='jadval rasmini yuklang', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='kechki',
            name='title',
            field=models.CharField(help_text='nomini kiriting', max_length=150),
        ),
    ]
